server:
  port: 8089

spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    inetutils:
      default-hostname: localhost
      default-ip-address: 127.0.0.1
    config:
        enabled: false

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: mappings